# Generated by Django 5.2.10 on 2026-01-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='name',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='description',
        ),
        migrations.AddField(
            model_name='organisation',
            name='contact_phone',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
