# Generated by Django 5.2.10 on 2026-02-02 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='company_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(default='unknown', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
