# Generated by Django 5.2.10 on 2026-03-16 05:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("complaint_id", models.CharField(blank=True, max_length=50)),
                ("user_email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("0", "0 - None"),
                            ("1", "1 - Very Low"),
                            ("2", "2 - Low"),
                            ("3", "3 - Medium"),
                            ("4", "4 - High"),
                            ("5", "5 - Critical"),
                        ],
                        default="0",
                        max_length=1,
                    ),
                ),
                ("ai_summary", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("WORKING", "Working On"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(blank=True, null=True, upload_to="complaints/"),
                ),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ComplaintUpdate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "complaint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updates",
                        to="core.complaint",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complaint",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="core.department",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentWork",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="New Work", max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("IN_PROGRESS", "In Progress"),
                            ("REQUESTED_CLOSE", "Requested Close"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="works",
                        to="core.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="complaint",
            name="works",
            field=models.ManyToManyField(
                blank=True, related_name="complaints", to="core.departmentwork"
            ),
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("isHod", models.BooleanField(default=False)),
                ("employee_id", models.CharField(max_length=20)),
                ("is_first_login", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="core.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="departmentwork",
            name="employees",
            field=models.ManyToManyField(
                blank=True, related_name="works", to="core.employee"
            ),
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organisation_logos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "organisation_type",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("government", "Government"),
                            ("ngo", "NGO"),
                            ("educational", "Educational"),
                        ],
                        max_length=20,
                    ),
                ),
                ("official_email", models.EmailField(max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["slug"], name="core_organi_slug_3088b1_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_owner", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manager_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="managers",
                        to="core.organisation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="core.organisation",
            ),
        ),
        migrations.AddField(
            model_name="departmentwork",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="works",
                to="core.organisation",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="core.organisation",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                to="core.organisation",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["organisation", "employee_id"],
                name="core_employ_organis_7239c3_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employee",
            unique_together={("organisation", "employee_id")},
        ),
        migrations.AddIndex(
            model_name="departmentwork",
            index=models.Index(
                fields=["organisation"], name="core_depart_organis_f64e8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organisation"], name="core_depart_organis_745215_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organisation", "name")},
        ),
        migrations.AddIndex(
            model_name="complaint",
            index=models.Index(
                fields=["organisation"], name="core_compla_organis_06547b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="complaint",
            unique_together={("organisation", "complaint_id")},
        ),
    ]
