# Generated by Django 5.2.10 on 2026-04-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_complaints', to='core.employee'),
        ),
    ]
