# Generated by Django 5.2.10 on 2026-02-16 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='managerid',
            new_name='manager_id',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AddField(
            model_name='manager',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
