# Generated by Django 5.2.10 on 2026-03-23 03:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("otp", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="employee",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
        migrations.AddField(
            model_name="organisation",
            name="cin",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="organisation",
            name="gstin",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="organisation",
            name="phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="organisation",
            name="website",
            field=models.URLField(blank=True),
        ),
    ]
