# Generated by Django 5.2.10 on 2026-01-20 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_complaint_department_complaint_closed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('WORKING', 'Working'), ('DONE', 'Done')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.AddField(
            model_name='complaint',
            name='works',
            field=models.ManyToManyField(blank=True, to='core.departmentwork'),
        ),
    ]
