# Generated by Django 5.2.10 on 2026-03-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organisation_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
