# Generated by Django 5.2.10 on 2026-03-02 19:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_description_organisation_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='isHod',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='departmentwork',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('REQUESTED_CLOSE', 'Requested Close'), ('CLOSED', 'Closed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
