# Generated by Django 5.2.10 on 2026-03-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_departmentwork_closed_at_departmentwork_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departmentwork',
            name='title',
            field=models.CharField(default='New Work', max_length=255),
        ),
    ]
