# Generated by Django 5.2.10 on 2026-03-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_otpverification_employee_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='cin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='organisation',
            name='gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='organisation',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
